# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
    -   repo: self

variables:
    tag: '$(Build.BuildId)'
    imageName: 'core-tenant'
    accountNamePrefix: 'thoud'

stages:
    -   stage: Build
        displayName: Build
        jobs:
            -   job: Api
                displayName: Api
                pool:
                    vmImage: 'ubuntu-latest'
                steps:
                    -   task: DockerInstaller@0
                        displayName: Install Docker
                        inputs:
                            dockerVersion: '17.09.0-ce'
                    -   task: Bash@3
                        displayName: Build Api
                        inputs:
                            targetType: 'inline'
                            script: 'docker build --tag gcr.io/$(accountNamePrefix)-production/$(imageName)-api:$(TAG) .'

                    -   task: Docker@2
                        displayName: Prod - GCR - Login
                        inputs:
                            command: login
                            containerRegistry: '$(accountNamePrefix)-production-gcr'
                    -   task: Bash@3
                        displayName: Prod - Push
                        inputs:
                            targetType: 'inline'
                            script: 'docker push gcr.io/$(accountNamePrefix)-production/$(imageName)-api:$(TAG)'
                    -   task: Docker@2
                        displayName: Prod - GCR - Logout
                        inputs:
                            command: logout
                            containerRegistry: '$(accountNamePrefix)-production-gcr'

    -   stage: Publish
        displayName: Publish Artifacts
        jobs:
            -   job: Terraform
                displayName: Terraform
                steps:
                    -   publish: $(System.DefaultWorkingDirectory)/infrastructure
                        artifact: infrastructure
